[package]
name = "helmo_b1_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
chrono = "0.4.43"
rand = "0.8.3"
serde = "1.0.228"
slint = "1.15.1"

[build-dependencies]
slint-build = "1.15.1"
