[workspace]
members = [
    "common",
    "q1_theory",
]

resolver = "2"

[workspace.dependencies]
bevy = "0.18.0"
bincode = "1.3"
chrono = "0.4.43"
rand = "0.8.3"
regex = "1.12.3"
serde = "1.0.228"
slint = "1.15.1"
slint-build = "1.15.1"
helmo_b1_rust = { path = "./common" }